// @momiji-rs/sparkdown-gfm — CommonMark + GitHub Flavored Markdown → HTML, as
// WASI-free WebAssembly. Same engine as @momiji-rs/sparkdown, compiled with the
// GFM extensions; render with `toHtml(md, options)`.
//
// The wasm module is base64-inlined (see ./wasm-inline.mjs, generated by
// build.mjs), so this package is self-contained: Node, browsers, bundlers,
// Deno, Bun, and edge runtimes, with no fetch, fs, or asset configuration.

import { WASM_BASE64 } from "./wasm-inline.mjs";

function base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(b64, "base64"));
  }
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

let wasm = null;
let initPromise = null;

/** Instantiate the wasm module (idempotent). Resolves to the raw exports. */
export function init() {
  if (wasm) return Promise.resolve(wasm);
  if (!initPromise) {
    initPromise = WebAssembly.instantiate(base64ToBytes(WASM_BASE64), {}).then(
      ({ instance }) => (wasm = instance.exports),
    );
  }
  return initPromise;
}

/** Resolves once the wasm module is ready; then `toHtmlSync` may be used. */
export const ready = init().then(() => {});

const encoder = new TextEncoder();
const decoder = new TextDecoder();

// Default: every GFM extension on (hard wraps off). Pass an options object to
// override individual flags, e.g. `toHtml(md, { tables: false })`.
const ALL = {
  strikethrough: true,
  tasklist: true,
  autolink: true,
  tagfilter: true,
  tables: true,
  hardWraps: false,
};

function toFlags(options) {
  const o = options ? { ...ALL, ...options } : ALL;
  return (
    (o.strikethrough ? 1 : 0) |
    (o.tasklist ? 2 : 0) |
    (o.autolink ? 4 : 0) |
    (o.tagfilter ? 8 : 0) |
    (o.tables ? 16 : 0) |
    (o.hardWraps ? 32 : 0)
  );
}

function render(ex, markdown, flags) {
  const input = encoder.encode(markdown);
  const inPtr = ex.sparkdown_alloc(input.length);
  // Re-read memory.buffer after each call that may grow (and detach) it.
  new Uint8Array(ex.memory.buffer).set(input, inPtr);
  const outPtr = ex.sparkdown_to_html_opts(inPtr, input.length, flags);
  const buf = ex.memory.buffer;
  const htmlLen = new DataView(buf).getUint32(outPtr, true);
  const html = decoder.decode(new Uint8Array(buf, outPtr + 4, htmlLen));
  ex.sparkdown_free(inPtr, input.length);
  ex.sparkdown_free(outPtr, 4 + htmlLen);
  return html;
}

/** Render `markdown` to HTML. `options` selects GFM extensions (default: all on). */
export async function toHtml(markdown, options) {
  return render(await init(), String(markdown), toFlags(options));
}

/** Synchronous render — valid only after `await ready` (or a prior `toHtml`). */
export function toHtmlSync(markdown, options) {
  if (!wasm) {
    throw new Error("sparkdown-gfm: await ready (or toHtml) before toHtmlSync");
  }
  return render(wasm, String(markdown), toFlags(options));
}

export default toHtml;
