// Generate npm/wasm-inline.mjs from a built sparkdown.wasm.
//
//   node build.mjs [path/to/sparkdown.wasm]
//
// Applies `wasm-opt -Oz` (binaryen) when available, then base64-inlines the
// module so the package is self-contained. The wasm itself must already be
// built (see the release workflow / README).
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const dir = dirname(fileURLToPath(import.meta.url));
const input =
  process.argv[2] ||
  join(dir, "..", "target", "wasm32-unknown-unknown", "release", "sparkdown.wasm");

let wasmPath = input;
try {
  const opt = join(dir, "sparkdown.opt.wasm");
  execFileSync(
    "wasm-opt",
    ["-O3", "--enable-simd", "--enable-bulk-memory", "--strip-debug", "--strip-producers", input, "-o", opt],
    { stdio: "pipe" },
  );
  wasmPath = opt;
  console.log("wasm-opt -Oz applied");
} catch {
  console.log("wasm-opt (binaryen) not found — inlining the raw wasm");
}

const bytes = readFileSync(wasmPath);
const b64 = bytes.toString("base64");
writeFileSync(
  join(dir, "wasm-inline.mjs"),
  "// Generated by build.mjs — do not edit. The sparkdown wasm module, base64.\n" +
    `export const WASM_BASE64 = ${JSON.stringify(b64)};\n`,
);
console.log(
  `wrote wasm-inline.mjs — ${(bytes.length / 1024).toFixed(1)} KB wasm, ` +
    `${(b64.length / 1024).toFixed(1)} KB base64`,
);
