// Inline a built wasm module into a base64 ESM file.
//
//   node build.mjs [path/to/.wasm] [output-name.mjs]
//
// Defaults to the release `sparkdown.wasm` → `wasm-inline.mjs`. This single
// package ships two variants, so the release/CI build calls it twice:
//   node build.mjs <pure .wasm> wasm-inline.mjs       # the `.` (CommonMark) entry
//   node build.mjs <gfm  .wasm> gfm-wasm-inline.mjs   # the `./gfm` entry
// Applies `wasm-opt -O3` (binaryen) when available. The .wasm must already be
// built (see the release workflow / README).
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const dir = dirname(fileURLToPath(import.meta.url));
const input =
  process.argv[2] ||
  join(dir, "..", "target", "wasm32-unknown-unknown", "release", "sparkdown.wasm");
const outName = process.argv[3] || "wasm-inline.mjs";

let wasmPath = input;
try {
  const opt = join(dir, "sparkdown.opt.wasm");
  execFileSync(
    "wasm-opt",
    ["-O3", "--enable-simd", "--enable-bulk-memory", "--strip-debug", "--strip-producers", input, "-o", opt],
    { stdio: "pipe" },
  );
  wasmPath = opt;
  console.log("wasm-opt -O3 (simd + bulk-memory) applied");
} catch {
  console.log("wasm-opt (binaryen) not found — inlining the raw wasm");
}

const bytes = readFileSync(wasmPath);
const b64 = bytes.toString("base64");
writeFileSync(
  join(dir, outName),
  "// Generated by build.mjs — do not edit. The sparkdown wasm module, base64.\n" +
    `export const WASM_BASE64 = ${JSON.stringify(b64)};\n`,
);
console.log(
  `wrote ${outName} — ${(bytes.length / 1024).toFixed(1)} KB wasm, ` +
    `${(b64.length / 1024).toFixed(1)} KB base64`,
);
