// @momiji-rs/sparkdown-gfm — CommonMark + GitHub Flavored Markdown → HTML, as
// WASI-free WebAssembly. Same engine as @momiji-rs/sparkdown, compiled with the
// GFM extensions; render with `toHtml(md, options)`.
//
// The wasm module is base64-inlined (see ./wasm-inline.mjs, generated by
// build.mjs), so this package is self-contained: Node, browsers, bundlers,
// Deno, Bun, and edge runtimes, with no fetch, fs, or asset configuration.

import { WASM_BASE64 } from "./gfm-wasm-inline.mjs";

function base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(b64, "base64"));
  }
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

let wasm = null;
let initPromise = null;

function instantiateSync() {
  // Synchronous compile + instantiate of the inlined module (no imports — WASI-free).
  return new WebAssembly.Instance(new WebAssembly.Module(base64ToBytes(WASM_BASE64)), {})
    .exports;
}

/**
 * Synchronously instantiate the wasm module (idempotent); afterwards `toHtmlSync`
 * works with no await. For Node / Bun / Deno / edge / workers — NOT the browser
 * main thread, where synchronous WebAssembly compilation is capped at ~4 KB (this
 * module is far larger and will throw); use `init()` / `ready` in browsers.
 */
export function initSync() {
  if (!wasm) wasm = instantiateSync();
  return wasm;
}

/** Instantiate the wasm module asynchronously (idempotent). Resolves to the exports. */
export function init() {
  if (wasm) return Promise.resolve(wasm);
  if (!initPromise) {
    initPromise = WebAssembly.instantiate(base64ToBytes(WASM_BASE64), {}).then(
      ({ instance }) => (wasm ??= instance.exports), // ??= so a prior initSync() isn't clobbered
    );
  }
  return initPromise;
}

/**
 * Resolves once the wasm module is ready; then `toHtmlSync` may be used. Lazy —
 * awaiting it (or calling `init`/`initSync`) is what instantiates, so importing
 * this package has no side effect.
 */
export const ready = {
  then: (onFulfilled, onRejected) => init().then(() => onFulfilled?.(), onRejected),
};

const encoder = new TextEncoder();
const decoder = new TextDecoder();

// Default: every GFM extension on (hard wraps off). Pass an options object to
// override individual flags, e.g. `toHtml(md, { tables: false })`.
const ALL = {
  strikethrough: true,
  tasklist: true,
  autolink: true,
  tagfilter: true,
  tables: true,
  hardWraps: false,
};

function toFlags(options) {
  const o = options ? { ...ALL, ...options } : ALL;
  return (
    (o.strikethrough ? 1 : 0) |
    (o.tasklist ? 2 : 0) |
    (o.autolink ? 4 : 0) |
    (o.tagfilter ? 8 : 0) |
    (o.tables ? 16 : 0) |
    (o.hardWraps ? 32 : 0)
  );
}

function render(ex, markdown, flags) {
  // Encode straight into wasm memory (no intermediate array, no copy); UTF-8 is
  // ≤ 3 bytes per UTF-16 code unit. The view re-reads memory.buffer after alloc.
  const cap = markdown.length * 3;
  const inPtr = ex.sparkdown_alloc(cap);
  const inLen = encoder.encodeInto(markdown, new Uint8Array(ex.memory.buffer, inPtr, cap)).written;
  const outPtr = ex.sparkdown_to_html_opts(inPtr, inLen, flags);
  const buf = ex.memory.buffer;
  const htmlLen = new DataView(buf).getUint32(outPtr, true);
  const html = decoder.decode(new Uint8Array(buf, outPtr + 4, htmlLen));
  ex.sparkdown_free(inPtr, cap);
  ex.sparkdown_free(outPtr, 4 + htmlLen);
  return html;
}

/** Render `markdown` to HTML. `options` selects GFM extensions (default: all on). */
export async function toHtml(markdown, options) {
  return render(await init(), String(markdown), toFlags(options));
}

/** Synchronous render — valid only after `await ready` (or a prior `toHtml`). */
export function toHtmlSync(markdown, options) {
  if (!wasm) {
    throw new Error("sparkdown-gfm: call initSync() or await ready/init() before toHtmlSync()");
  }
  return render(wasm, String(markdown), toFlags(options));
}

export default toHtml;
