// sparkdown — fast, standards-first CommonMark → HTML, as WASI-free WebAssembly.
//
// The wasm module is base64-inlined (see ./wasm-inline.mjs, generated by
// build.mjs), so this package is self-contained: it works in Node, browsers,
// bundlers, Deno, and edge runtimes with no fetch, fs, or asset configuration.

import { WASM_BASE64 } from "./wasm-inline.mjs";

function base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(b64, "base64"));
  }
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

let wasm = null;
let initPromise = null;

/** Instantiate the wasm module (idempotent). Resolves to the raw exports. */
export function init() {
  if (wasm) return Promise.resolve(wasm);
  if (!initPromise) {
    initPromise = WebAssembly.instantiate(base64ToBytes(WASM_BASE64), {}).then(
      ({ instance }) => (wasm = instance.exports),
    );
  }
  return initPromise;
}

/** Resolves once the wasm module is ready; then `toHtmlSync` may be used. */
export const ready = init().then(() => {});

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function render(ex, markdown) {
  const input = encoder.encode(markdown);
  const inPtr = ex.sparkdown_alloc(input.length);
  // Re-read memory.buffer after each call that may grow (and detach) it.
  new Uint8Array(ex.memory.buffer).set(input, inPtr);
  const outPtr = ex.sparkdown_to_html(inPtr, input.length);
  const buf = ex.memory.buffer;
  const htmlLen = new DataView(buf).getUint32(outPtr, true);
  const html = decoder.decode(new Uint8Array(buf, outPtr + 4, htmlLen));
  ex.sparkdown_free(inPtr, input.length);
  ex.sparkdown_free(outPtr, 4 + htmlLen);
  return html;
}

/** Render CommonMark `markdown` to an HTML string. */
export async function toHtml(markdown) {
  return render(await init(), String(markdown));
}

/** Synchronous render — valid only after `await ready` (or a prior `toHtml`). */
export function toHtmlSync(markdown) {
  if (!wasm) {
    throw new Error("sparkdown: await ready (or toHtml) before toHtmlSync");
  }
  return render(wasm, String(markdown));
}

export default toHtml;
