// sparkdown — fast, standards-first CommonMark → HTML, as WASI-free WebAssembly.
//
// The wasm module is base64-inlined (see ./wasm-inline.mjs, generated by
// build.mjs), so this package is self-contained: it works in Node, browsers,
// bundlers, Deno, and edge runtimes with no fetch, fs, or asset configuration.

import { WASM_BASE64 } from "./wasm-inline.mjs";

function base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(b64, "base64"));
  }
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

let wasm = null;
let initPromise = null;

function instantiateSync() {
  // Synchronous compile + instantiate of the inlined module (no imports — WASI-free).
  return new WebAssembly.Instance(new WebAssembly.Module(base64ToBytes(WASM_BASE64)), {})
    .exports;
}

/**
 * Synchronously instantiate the wasm module (idempotent); afterwards `toHtmlSync`
 * works with no await. For Node / Bun / Deno / edge / workers — NOT the browser
 * main thread, where synchronous WebAssembly compilation is capped at ~4 KB (this
 * module is far larger and will throw); use `init()` / `ready` in browsers.
 */
export function initSync() {
  if (!wasm) wasm = instantiateSync();
  return wasm;
}

/** Instantiate the wasm module asynchronously (idempotent). Resolves to the exports. */
export function init() {
  if (wasm) return Promise.resolve(wasm);
  if (!initPromise) {
    initPromise = WebAssembly.instantiate(base64ToBytes(WASM_BASE64), {}).then(
      ({ instance }) => (wasm ??= instance.exports), // ??= so a prior initSync() isn't clobbered
    );
  }
  return initPromise;
}

/**
 * Resolves once the wasm module is ready; then `toHtmlSync` may be used. Lazy —
 * awaiting it (or calling `init`/`initSync`) is what instantiates, so importing
 * this package has no side effect.
 */
export const ready = {
  then: (onFulfilled, onRejected) => init().then(() => onFulfilled?.(), onRejected),
};

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function render(ex, markdown) {
  const input = encoder.encode(markdown);
  const inPtr = ex.sparkdown_alloc(input.length);
  // Re-read memory.buffer after each call that may grow (and detach) it.
  new Uint8Array(ex.memory.buffer).set(input, inPtr);
  const outPtr = ex.sparkdown_to_html(inPtr, input.length);
  const buf = ex.memory.buffer;
  const htmlLen = new DataView(buf).getUint32(outPtr, true);
  const html = decoder.decode(new Uint8Array(buf, outPtr + 4, htmlLen));
  ex.sparkdown_free(inPtr, input.length);
  ex.sparkdown_free(outPtr, 4 + htmlLen);
  return html;
}

/** Render CommonMark `markdown` to an HTML string. */
export async function toHtml(markdown) {
  return render(await init(), String(markdown));
}

/** Synchronous render — valid only after `await ready` (or a prior `toHtml`). */
export function toHtmlSync(markdown) {
  if (!wasm) {
    throw new Error("sparkdown: call initSync() or await ready/init() before toHtmlSync()");
  }
  return render(wasm, String(markdown));
}

export default toHtml;
